Import 2.6.31-2.0 release

diff --git a/uclinux-rootfs/user/busybox/scripts/trylink b/uclinux-rootfs/user/busybox/scripts/trylink
--- a/uclinux-rootfs/user/busybox/scripts/trylink
+++ b/uclinux-rootfs/user/busybox/scripts/trylink
@@ -41,9 +41,8 @@ try() {
     printf "%s\n" "$*" >>$EXE.out
     printf "%s\n" "==========" >>$EXE.out
     $debug && echo "Trying: $*"
-    "$@" >>$EXE.out 2>&1
-    exitcode=$?
-    return $exitcode
+    $@ >>$EXE.out 2>&1
+    return $?
 }
 
 check_cc() {
@@ -100,6 +99,11 @@ else
 fi
 )`
 
+# The --gc-sections option is not supported by older versions of ld
+if test -n "$GC_SECTIONS"; then
+    GC_SECTIONS=`check_cc "$GC_SECTIONS" ""`
+fi
+
 # Sanitize lib list (dups, extra spaces etc)
 LDLIBS=`echo "$LDLIBS" | xargs -n1 | sort | uniq | xargs`
 
@@ -141,12 +145,12 @@ while test "$LDLIBS"; do
 		-Wl,--start-group $O_FILES $A_FILES -Wl,--end-group \
 		$l_list
 	if test $? = 0; then
-	    echo " Library $one is not needed"
+	    echo " Library $one is not needed, excluding it"
 	    LDLIBS="$without_one"
 	    all_needed=false
 	    last_needed=false
 	else
-	    echo " Library $one is needed"
+	    echo " Library $one is needed, can't exclude it (yet)"
 	    last_needed=true
 	fi
     done
