Import 2.6.31-1.0 release

diff --git a/uclinux-rootfs/Makefile b/uclinux-rootfs/Makefile
--- a/uclinux-rootfs/Makefile
+++ b/uclinux-rootfs/Makefile
@@ -18,7 +18,7 @@
 #
 
 SAVEVARS	:= PATH SHELL HOME USER MFLAGS MAKEFLAGS MAKELEVEL \
-		MAKEOVERRIDES TERM
+		MAKEOVERRIDES TERM DISPLAY
 unexport $(shell perl -w bin/cleanenv.pl $(SAVEVARS))
 
 # don't pass command line options like SUBDIRS
@@ -45,7 +45,6 @@ export ROOTDIR LINUXDIR LINUX_CONFIG CONFIG_CONFIG ARCH_CONFIG ROMFSDIR \
 
 TFTPHOST	:= $(shell hostname)
 TFTPDIR		:= $$USER
-MAKEOPTS	:= TFTPHOST=$(TFTPHOST) TFTPDIR=$(TFTPDIR)
 TFTPBOOT	:= /tftpboot/$(TFTPDIR)
 
 PLAT		:= $(shell cat .target 2> /dev/null)
@@ -56,13 +55,26 @@ REL_TFTPHOST	:= stb-irva-01
 REL_TFTPDIR	:= $(VERSION)
 RELOPTS		:= TFTPHOST=$(REL_TFTPHOST) TFTPDIR=$(REL_TFTPDIR)
 
+# note that these are also hard-coded into config.pl
+NONFREE_BIN	:= $(ROOTDIR)/../nonfree
+NONFREE_SRC	:= $(ROOTDIR)/../nonfree_src
+NONFREE_PLAT	:= $(firstword $(subst -, ,$(PLAT)))
+NONFREE_DESTDIR	:= $(NONFREE_BIN)/$(NONFREE_PLAT)
+
+MAKEOPTS	:= TFTPHOST=$(TFTPHOST) TFTPDIR=$(TFTPDIR)
+
 #############################################################################
 # BASIC KERNEL/ROOTFS BUILDS
 #############################################################################
 
 .PHONY: images
 images: .target
-	$(MAKE) $(MAKEOPTS) initrd_kernel kernel
+	# initrd_kernel implicitly builds kernel in this case
+	@if $(CFG) test_vendor CONFIG_USER_NONFREE_USES_KBUILD; then \
+		$(MAKE) $(MAKEOPTS) initrd_kernel || exit 1 ; \
+	else \
+		$(MAKE) $(MAKEOPTS) initrd_kernel kernel || exit 1 ; \
+	fi
 	bin/build_rootfs_images.sh
 	@echo ""
 	@echo "Build complete.  Images are in images/"
@@ -72,6 +84,7 @@ images: .target
 
 .PHONY: initrd_kernel
 initrd_kernel: .target chkpath
+	mkdir -p images
 	# prepare rootfs skeleton
 	if [ -z "$(SUBDIRS)" ]; then \
 		rm -rf $(ROMFSDIR) ; \
@@ -90,6 +103,37 @@ initrd_kernel: .target chkpath
 		echo "PLAT=$(PLAT)" >> romfs/etc/brcmstb.conf ; \
 		echo "VERSION=$(VERSION)" >> romfs/etc/brcmstb.conf ; \
 	fi
+	# build non-initrd kernel for drivers that need Module.symvers
+	if $(CFG) test_vendor CONFIG_USER_NONFREE_USES_KBUILD; then \
+		$(MAKE) kernel || exit 1 ; \
+	fi
+	# build nonfree components from source, then create binary tarball
+	if $(CFG) test_vendor CONFIG_USER_NONFREE_SRC; then \
+		if $(CFG) test_vendor CONFIG_USER_NONFREE_MOCA_SRC; then \
+			rm -rf $(NONFREE_DESTDIR)/moca ; \
+			$(MAKE) -C $(NONFREE_SRC)/moca ROOTDIR=$(ROOTDIR) \
+				DESTDIR=$(NONFREE_DESTDIR)/moca \
+				nonfree-$(NONFREE_PLAT) || exit 1 ; \
+		fi ; \
+		if $(CFG) test_vendor CONFIG_USER_NONFREE_WLAN_SRC; then \
+			rm -rf $(NONFREE_DESTDIR)/wlan ; \
+			$(MAKE) -C $(NONFREE_SRC)/wlan ROOTDIR=$(ROOTDIR) \
+				DESTDIR=$(NONFREE_DESTDIR)/wlan \
+				nonfree-$(NONFREE_PLAT) || exit 1 ; \
+		fi ; \
+		tar -C $(NONFREE_BIN)/.. -jcf images/nonfree-$(PLAT).tar.bz2 \
+			nonfree/$(NONFREE_PLAT) || exit 1 ; \
+	fi
+	# copy nonfree binaries (if present) into place
+	rm -rf user/nonfree/{moca,wlan}
+	if $(CFG) test_vendor CONFIG_USER_NONFREE_MOCA; then \
+		cp -a $(NONFREE_BIN)/$(NONFREE_PLAT)/moca user/nonfree/ \
+			|| exit 1 ; \
+	fi
+	if $(CFG) test_vendor CONFIG_USER_NONFREE_WLAN; then \
+		cp -a $(NONFREE_BIN)/$(NONFREE_PLAT)/wlan user/nonfree/ \
+			|| exit 1 ; \
+	fi
 	# build/install rootfs contents
 	if [[ "$(SUBDIRS)" != "linux*" ]]; then \
 		$(MAKE) -C lib all romfs \
@@ -101,7 +145,6 @@ initrd_kernel: .target chkpath
 	$(CFG) initramfs
 	$(MAKE) -C $(LINUXDIR) vmlinux
 	# copy completed gzipped kernel to images/
-	mkdir -p images
 	gzip -9 < $(LINUXDIR)/vmlinux > \
 		images/vmlinuz-initrd-$(PLAT)
 
@@ -137,10 +180,18 @@ images-%:
 
 .PHONY: release
 release:
+	# make sure this is a clean view
 	@if [ -e .dirty -o -e images -o -e release ]; then \
 		echo "ERROR: \"make release\" must be run on a pristine view" ; \
 		exit 1 ; \
 	fi
+	# check for nonfree sources
+	if [ ! -d ../../LinuxSupport/nonfree_src ]; then \
+		echo "ERROR: missing nonfree sources" ; \
+		exit 1 ; \
+	fi
+	ln -sf ../LinuxSupport/nonfree_src ../nonfree_src
+	# unpack tarballs/* then build pristine source tarballs for release
 	cd .. ; perl -w tools/unpack.pl -r || exit 1
 	chmod -R u+w . linux-2.6.x/
 	chmod -R 0755 bin/
@@ -148,11 +199,18 @@ release:
 		export STBLINUX=`basename $$LINK`; \
 		tar -C .. -jcf ../stblinux-$(DOTVERSION).tar.bz2 $$STBLINUX
 	tar -C .. -jcf ../uclinux-rootfs-$(DOTVERSION).tar.bz2 uclinux-rootfs
-	# $(MAKE) -C ../../LinuxSupport/nonfree install ROOTDIR=$(ROOTDIR)
-	# tar -C .. -jcf ../nonfree-$(DOTVERSION).tar.bz2 nonfree
+	# build pristine nonfree source tarballs
+	chmod -R u+w $(NONFREE_SRC)/
+	mkdir -p RESTRICTED
+	tar -C .. -jcf RESTRICTED/moca_src-$(DOTVERSION).tar.bz2 \
+		nonfree_src/moca/
+	tar -C .. -jcf RESTRICTED/wlan_src-$(DOTVERSION).tar.bz2 \
+		nonfree_src/wlan/
+	# build all platforms
 	for x in $(shell cat misc/release_builds); do \
 		$(MAKE) $(RELOPTS) images-$$x || exit 1; \
 	done
+	# move files into the release directory
 	mkdir -p release/src
 	mv ../stblinux-$(DOTVERSION).tar.bz2 \
 		../uclinux-rootfs-$(DOTVERSION).tar.bz2 \
@@ -199,12 +257,41 @@ defaults-%: chkpath
 	@chmod -R 0755 config/scripts/{Configure,Menuconfig} bin
 	$(CFG) defaults $*
 	$(MAKE) silentoldconfig
+	@echo "***************************************************************"
+	@echo "* Build configuration"
+	@echo "*"
+	@echo "* Target:                  $*"
+	@echo "* Version:                 $(DOTVERSION)"
+	@echo "* TFTP host:               $(TFTPHOST)"
+	@echo "* Remote TFTP path:        $(TFTPDIR)"
+	@echo "* Local TFTP path:         $(TFTPBOOT)"
+	@if $(CFG) test_vendor CONFIG_USER_NONFREE_MOCA; then \
+		if $(CFG) test_vendor CONFIG_USER_NONFREE_MOCA_SRC; then \
+			echo "* MoCA drivers:            Building from source" ; \
+		else \
+			echo "* MoCA drivers:            Using precompiled binaries" ; \
+		fi ; \
+	else \
+		echo "* MoCA drivers:            NOT ENABLED" ; \
+	fi
+	@if $(CFG) test_vendor CONFIG_USER_NONFREE_WLAN; then \
+		if $(CFG) test_vendor CONFIG_USER_NONFREE_WLAN_SRC; then \
+			echo "* WLAN drivers:            Building from source" ; \
+		else \
+			echo "* WLAN drivers:            Using precompiled binaries" ; \
+		fi ; \
+	else \
+		echo "* WLAN drivers:            NOT ENABLED" ; \
+	fi
+	@echo "***************************************************************"
+	@echo ""
 
 .PHONY: save_defaults
 save_defaults: .target
 	$(CFG) save_defaults $(PLAT)
 
-.PHONY: menuconfig-linux menuconfig-vendor menuconfig-uclibc menuconfig-busybox
+.PHONY: menuconfig-linux menuconfig-vendor menuconfig-uclibc \
+	menuconfig-busybox xconfig-linux
 menuconfig-linux: .target
 	$(MAKE) -C $(LINUXDIR) menuconfig
 
@@ -216,6 +303,9 @@ menuconfig-uclibc: .target
 
 menuconfig-busybox: .target
 	$(MAKE) -C user/busybox menuconfig
+
+xconfig-linux: .target
+	$(MAKE) -C $(LINUXDIR) xconfig
 
 #############################################################################
 # INSTALL/CLEAN
@@ -229,6 +319,17 @@ install:
 	@echo "Images have been copied to $(TFTPBOOT)"
 	@echo ""
 
+.PHONY: nonfree_clean
+nonfree_clean:
+	if $(CFG) test_vendor CONFIG_USER_NONFREE_MOCA_SRC; then \
+		make -C $(NONFREE_SRC)/moca ROOTDIR=$(ROOTDIR) \
+			DESTDIR=$(NONFREE_DESTDIR)/moca clean || exit 1 ; \
+	fi
+	if $(CFG) test_vendor CONFIG_USER_NONFREE_WLAN_SRC; then \
+		make -C $(NONFREE_SRC)/wlan ROOTDIR=$(ROOTDIR) \
+			DESTDIR=$(NONFREE_DESTDIR)/wlan clean || exit 1 ; \
+	fi
+
 .PHONY: clean
 clean:
 	if [ -e .target ]; then \
@@ -236,6 +337,7 @@ clean:
 			$(MAKE) -C lib clean ; \
 			$(MAKE) -C user clean ; \
 			$(MAKE) -C $(LINUXDIR) clean ; \
+			$(MAKE) $(MAKEOPTS) nonfree_clean ; \
 		elif [[ "$(SUBDIRS)" != "linux*" ]]; then \
 			$(MAKE) -C lib clean \
 				INITRD_SUBDIR="$(SUBDIRS)" || exit 1 ; \
@@ -253,6 +355,7 @@ distclean:
 		$(MAKE) -C user distclean clean ; \
 		$(MAKE) -C $(LINUXDIR) mrproper ; \
 		$(MAKE) -C config clean ; \
+		$(MAKE) $(MAKEOPTS) nonfree_clean ; \
 	fi
 	rm -rf romfs tmp
 	rm -f $(CONFIG_CONFIG) $(ARCH_CONFIG) .target
